# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Install Dependencies'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      fetchDepth: 0  # Fetches all history
    - script: |
        npm install
      displayName: 'Install dependencies'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: |
        npm test
      displayName: 'Run Unit Tests'
      
- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'myConnection'
        appName: 'myFunctionApps01'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'

